// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xdvnode/documents.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Documents struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id           uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Hash         string `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	LastModified uint64 `protobuf:"varint,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	ContentType  string `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Signature    string `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	Network      string `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	Did          string `protobuf:"bytes,9,opt,name=did,proto3" json:"did,omitempty"`
	Alg          string `protobuf:"bytes,10,opt,name=alg,proto3" json:"alg,omitempty"`
	Pinned       bool   `protobuf:"varint,11,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Tokenized    bool   `protobuf:"varint,12,opt,name=tokenized,proto3" json:"tokenized,omitempty"`
	MetadataURI  string `protobuf:"bytes,13,opt,name=metadataURI,proto3" json:"metadataURI,omitempty"`
}

func (m *Documents) Reset()         { *m = Documents{} }
func (m *Documents) String() string { return proto.CompactTextString(m) }
func (*Documents) ProtoMessage()    {}
func (*Documents) Descriptor() ([]byte, []int) {
	return fileDescriptor_9acd19b8810ea64d, []int{0}
}
func (m *Documents) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Documents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Documents.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Documents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Documents.Merge(m, src)
}
func (m *Documents) XXX_Size() int {
	return m.Size()
}
func (m *Documents) XXX_DiscardUnknown() {
	xxx_messageInfo_Documents.DiscardUnknown(m)
}

var xxx_messageInfo_Documents proto.InternalMessageInfo

func (m *Documents) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Documents) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Documents) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Documents) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Documents) GetLastModified() uint64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Documents) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Documents) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Documents) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Documents) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *Documents) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

func (m *Documents) GetPinned() bool {
	if m != nil {
		return m.Pinned
	}
	return false
}

func (m *Documents) GetTokenized() bool {
	if m != nil {
		return m.Tokenized
	}
	return false
}

func (m *Documents) GetMetadataURI() string {
	if m != nil {
		return m.MetadataURI
	}
	return ""
}

func init() {
	proto.RegisterType((*Documents)(nil), "ElectronicSignaturesIndustries.xdvnode.xdvnode.Documents")
}

func init() { proto.RegisterFile("xdvnode/documents.proto", fileDescriptor_9acd19b8810ea64d) }

var fileDescriptor_9acd19b8810ea64d = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x31, 0x73, 0xda, 0x30,
	0x14, 0x80, 0xb1, 0xa1, 0x80, 0x05, 0xf4, 0x7a, 0x1a, 0x5a, 0x0d, 0x3d, 0x9f, 0xdb, 0x2e, 0x2c,
	0xd8, 0x43, 0xff, 0x41, 0x8f, 0x0e, 0x0c, 0x59, 0x9c, 0x64, 0xc9, 0x10, 0x4e, 0x58, 0x2f, 0x46,
	0x87, 0x2d, 0xf9, 0x2c, 0x99, 0x40, 0x7e, 0x45, 0x7e, 0x56, 0x46, 0xc6, 0x64, 0xcb, 0xc1, 0x1f,
	0xc9, 0x49, 0xb6, 0xcf, 0x99, 0xf4, 0xde, 0xf7, 0xa4, 0xa7, 0x27, 0x7d, 0xe8, 0xc7, 0x81, 0xed,
	0x85, 0x64, 0x10, 0x31, 0x99, 0x54, 0x39, 0x08, 0xad, 0xc2, 0xa2, 0x94, 0x5a, 0xe2, 0xf0, 0x7f,
	0x06, 0x89, 0x2e, 0xa5, 0xe0, 0xc9, 0x35, 0x4f, 0x05, 0xd5, 0x55, 0x09, 0x6a, 0x25, 0x58, 0xa5,
	0x74, 0xc9, 0x41, 0x85, 0xcd, 0xb9, 0x76, 0xfd, 0xfd, 0xe6, 0x22, 0x6f, 0xd9, 0xf6, 0xc0, 0x04,
	0x8d, 0x92, 0x12, 0xa8, 0x96, 0x25, 0x71, 0x02, 0x67, 0xee, 0xc5, 0x6d, 0x8a, 0xbf, 0x22, 0x97,
	0x33, 0xe2, 0x06, 0xce, 0x7c, 0x10, 0xbb, 0x9c, 0x61, 0x8c, 0x06, 0x82, 0xe6, 0x40, 0xfa, 0x76,
	0x9b, 0x8d, 0x0d, 0xdb, 0x52, 0xb5, 0x25, 0x83, 0x9a, 0x99, 0x18, 0xff, 0x41, 0xb3, 0x8c, 0x2a,
	0xbd, 0xce, 0x25, 0xe3, 0x0f, 0x1c, 0x18, 0xf9, 0x62, 0x5b, 0x4c, 0x0d, 0xbc, 0x6a, 0x18, 0xfe,
	0x85, 0xa6, 0x89, 0x14, 0x1a, 0x84, 0x5e, 0xeb, 0x63, 0x01, 0x64, 0x68, 0x1b, 0x4c, 0x1a, 0x76,
	0x73, 0x2c, 0x00, 0xff, 0x44, 0x9e, 0x6a, 0xdf, 0x43, 0x46, 0xb6, 0xde, 0x01, 0x33, 0xb7, 0x00,
	0xfd, 0x28, 0xcb, 0x1d, 0x19, 0xd7, 0x73, 0x37, 0x29, 0xfe, 0x86, 0xfa, 0x8c, 0x33, 0xe2, 0x59,
	0x6a, 0x42, 0x43, 0x68, 0x96, 0x12, 0x54, 0x13, 0x9a, 0xa5, 0xf8, 0x3b, 0x1a, 0x16, 0x5c, 0x08,
	0x60, 0x64, 0x12, 0x38, 0xf3, 0x71, 0xdc, 0x64, 0xe6, 0x4e, 0x2d, 0x77, 0x20, 0xf8, 0x13, 0x30,
	0x32, 0xb5, 0xa5, 0x0e, 0xe0, 0x00, 0x4d, 0x72, 0xd0, 0x94, 0x51, 0x4d, 0x6f, 0xe3, 0x15, 0x99,
	0xd5, 0x33, 0x7f, 0x42, 0xff, 0xee, 0x5f, 0xce, 0xbe, 0x73, 0x3a, 0xfb, 0xce, 0xfb, 0xd9, 0x77,
	0x9e, 0x2f, 0x7e, 0xef, 0x74, 0xf1, 0x7b, 0xaf, 0x17, 0xbf, 0x77, 0xb7, 0x4c, 0xb9, 0xde, 0x56,
	0x9b, 0x30, 0x91, 0x79, 0xd4, 0x09, 0x5b, 0x74, 0xc6, 0x16, 0x9d, 0xb2, 0xe8, 0xc0, 0xf6, 0x0b,
	0xeb, 0xfa, 0x10, 0xb5, 0xd6, 0xcd, 0x2f, 0xa9, 0xcd, 0xd0, 0x2a, 0xff, 0xfb, 0x11, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0x1e, 0xb2, 0x7e, 0x0d, 0x02, 0x00, 0x00,
}

func (m *Documents) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Documents) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Documents) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetadataURI) > 0 {
		i -= len(m.MetadataURI)
		copy(dAtA[i:], m.MetadataURI)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.MetadataURI)))
		i--
		dAtA[i] = 0x6a
	}
	if m.Tokenized {
		i--
		if m.Tokenized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.Pinned {
		i--
		if m.Pinned {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if len(m.Alg) > 0 {
		i -= len(m.Alg)
		copy(dAtA[i:], m.Alg)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.Alg)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Network) > 0 {
		i -= len(m.Network)
		copy(dAtA[i:], m.Network)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.Network)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ContentType) > 0 {
		i -= len(m.ContentType)
		copy(dAtA[i:], m.ContentType)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.ContentType)))
		i--
		dAtA[i] = 0x32
	}
	if m.LastModified != 0 {
		i = encodeVarintDocuments(dAtA, i, uint64(m.LastModified))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Id != 0 {
		i = encodeVarintDocuments(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintDocuments(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDocuments(dAtA []byte, offset int, v uint64) int {
	offset -= sovDocuments(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Documents) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovDocuments(uint64(m.Id))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	if m.LastModified != 0 {
		n += 1 + sovDocuments(uint64(m.LastModified))
	}
	l = len(m.ContentType)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	l = len(m.Network)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	l = len(m.Alg)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	if m.Pinned {
		n += 2
	}
	if m.Tokenized {
		n += 2
	}
	l = len(m.MetadataURI)
	if l > 0 {
		n += 1 + l + sovDocuments(uint64(l))
	}
	return n
}

func sovDocuments(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDocuments(x uint64) (n int) {
	return sovDocuments(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Documents) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDocuments
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Documents: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Documents: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastModified", wireType)
			}
			m.LastModified = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastModified |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Network = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pinned", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Pinned = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokenized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tokenized = bool(v != 0)
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataURI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDocuments
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDocuments
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataURI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDocuments(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDocuments
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDocuments(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDocuments
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDocuments
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDocuments
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDocuments
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDocuments
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDocuments        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDocuments          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDocuments = fmt.Errorf("proto: unexpected end of group")
)
