// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: xdvnode/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetDocumentsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDocumentsRequest) Reset()         { *m = QueryGetDocumentsRequest{} }
func (m *QueryGetDocumentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDocumentsRequest) ProtoMessage()    {}
func (*QueryGetDocumentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8e2c1b9bdbca1d, []int{0}
}
func (m *QueryGetDocumentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDocumentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDocumentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDocumentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDocumentsRequest.Merge(m, src)
}
func (m *QueryGetDocumentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDocumentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDocumentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDocumentsRequest proto.InternalMessageInfo

func (m *QueryGetDocumentsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetDocumentsResponse struct {
	Documents *Documents `protobuf:"bytes,1,opt,name=Documents,proto3" json:"Documents,omitempty"`
}

func (m *QueryGetDocumentsResponse) Reset()         { *m = QueryGetDocumentsResponse{} }
func (m *QueryGetDocumentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDocumentsResponse) ProtoMessage()    {}
func (*QueryGetDocumentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8e2c1b9bdbca1d, []int{1}
}
func (m *QueryGetDocumentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDocumentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDocumentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDocumentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDocumentsResponse.Merge(m, src)
}
func (m *QueryGetDocumentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDocumentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDocumentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDocumentsResponse proto.InternalMessageInfo

func (m *QueryGetDocumentsResponse) GetDocuments() *Documents {
	if m != nil {
		return m.Documents
	}
	return nil
}

type QueryAllDocumentsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDocumentsRequest) Reset()         { *m = QueryAllDocumentsRequest{} }
func (m *QueryAllDocumentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDocumentsRequest) ProtoMessage()    {}
func (*QueryAllDocumentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8e2c1b9bdbca1d, []int{2}
}
func (m *QueryAllDocumentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDocumentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDocumentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDocumentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDocumentsRequest.Merge(m, src)
}
func (m *QueryAllDocumentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDocumentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDocumentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDocumentsRequest proto.InternalMessageInfo

func (m *QueryAllDocumentsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDocumentsResponse struct {
	Documents  []*Documents        `protobuf:"bytes,1,rep,name=Documents,proto3" json:"Documents,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDocumentsResponse) Reset()         { *m = QueryAllDocumentsResponse{} }
func (m *QueryAllDocumentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDocumentsResponse) ProtoMessage()    {}
func (*QueryAllDocumentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8e2c1b9bdbca1d, []int{3}
}
func (m *QueryAllDocumentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDocumentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDocumentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDocumentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDocumentsResponse.Merge(m, src)
}
func (m *QueryAllDocumentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDocumentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDocumentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDocumentsResponse proto.InternalMessageInfo

func (m *QueryAllDocumentsResponse) GetDocuments() []*Documents {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *QueryAllDocumentsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetDocumentsRequest)(nil), "ElectronicSignaturesIndustries.xdvnode.xdvnode.QueryGetDocumentsRequest")
	proto.RegisterType((*QueryGetDocumentsResponse)(nil), "ElectronicSignaturesIndustries.xdvnode.xdvnode.QueryGetDocumentsResponse")
	proto.RegisterType((*QueryAllDocumentsRequest)(nil), "ElectronicSignaturesIndustries.xdvnode.xdvnode.QueryAllDocumentsRequest")
	proto.RegisterType((*QueryAllDocumentsResponse)(nil), "ElectronicSignaturesIndustries.xdvnode.xdvnode.QueryAllDocumentsResponse")
}

func init() { proto.RegisterFile("xdvnode/query.proto", fileDescriptor_3f8e2c1b9bdbca1d) }

var fileDescriptor_3f8e2c1b9bdbca1d = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0xaa, 0xd3, 0x40,
	0x18, 0x85, 0x3b, 0xa9, 0x0a, 0x8e, 0xe2, 0x62, 0x5c, 0x58, 0x8b, 0x04, 0xc9, 0x42, 0xa5, 0xd0,
	0x19, 0x5a, 0x57, 0x22, 0x82, 0xad, 0xd5, 0xb6, 0x3b, 0xad, 0x0b, 0xc1, 0x85, 0x30, 0x49, 0x86,
	0x38, 0x90, 0xce, 0xa4, 0x99, 0x49, 0xb1, 0x88, 0x1b, 0x9f, 0x40, 0xf0, 0x79, 0xdc, 0xbb, 0x2c,
	0xb8, 0x71, 0xa7, 0xb4, 0x2e, 0xe4, 0x3e, 0xc5, 0xa5, 0xc9, 0xa4, 0x69, 0x69, 0x2e, 0xf7, 0xb6,
	0xb7, 0xab, 0x40, 0xf2, 0xff, 0xe7, 0x7c, 0xe7, 0xe7, 0x10, 0x78, 0xfb, 0x93, 0x3f, 0x15, 0xd2,
	0x67, 0x64, 0x92, 0xb0, 0x78, 0x86, 0xa3, 0x58, 0x6a, 0x89, 0xf0, 0xcb, 0x90, 0x79, 0x3a, 0x96,
	0x82, 0x7b, 0x6f, 0x79, 0x20, 0xa8, 0x4e, 0x62, 0xa6, 0x86, 0xc2, 0x4f, 0x94, 0x8e, 0x39, 0x53,
	0xd8, 0xec, 0xe4, 0xcf, 0xfa, 0xbd, 0x40, 0xca, 0x20, 0x64, 0x84, 0x46, 0x9c, 0x50, 0x21, 0xa4,
	0xa6, 0x9a, 0x4b, 0xa1, 0x32, 0xb5, 0x7a, 0xc3, 0x93, 0x6a, 0x2c, 0x15, 0x71, 0xa9, 0x32, 0x36,
	0x64, 0xda, 0x72, 0x99, 0xa6, 0x2d, 0x12, 0xd1, 0x80, 0x8b, 0x74, 0xd8, 0xcc, 0xde, 0xc9, 0x71,
	0x7c, 0xe9, 0x25, 0x63, 0x26, 0xb4, 0x11, 0x71, 0x1a, 0xb0, 0xf6, 0x66, 0xb5, 0xda, 0x67, 0xba,
	0x97, 0x7f, 0x1a, 0xb1, 0x49, 0xc2, 0x94, 0x46, 0xb7, 0xa0, 0xc5, 0xfd, 0x1a, 0xb8, 0x0f, 0x1e,
	0x5d, 0x19, 0x59, 0xdc, 0x77, 0x34, 0xbc, 0x5b, 0x32, 0xab, 0x22, 0x29, 0x14, 0x43, 0xef, 0xe0,
	0xf5, 0xf5, 0xcb, 0x74, 0xe7, 0x46, 0xfb, 0xc9, 0x9e, 0x79, 0x71, 0xa1, 0x5a, 0x68, 0x39, 0xae,
	0x21, 0xec, 0x84, 0xe1, 0x0e, 0xe1, 0x2b, 0x08, 0x8b, 0xa8, 0xc6, 0xf5, 0x01, 0xce, 0xee, 0x82,
	0x57, 0x77, 0xc1, 0xd9, 0xf9, 0xcd, 0x5d, 0xf0, 0x6b, 0x1a, 0x30, 0xb3, 0x3b, 0xda, 0xd8, 0x74,
	0x7e, 0x00, 0x13, 0x6d, 0xdb, 0xa4, 0x3c, 0x5a, 0xf5, 0x58, 0xd1, 0x50, 0x7f, 0x0b, 0xdf, 0x4a,
	0xf1, 0x1f, 0x9e, 0x8b, 0x9f, 0x51, 0x6d, 0xf2, 0xb7, 0xff, 0x54, 0xe1, 0xd5, 0x94, 0x1f, 0x9d,
	0x80, 0x0d, 0x58, 0x34, 0xd8, 0x17, 0xf3, 0xac, 0x2e, 0xd4, 0x87, 0x47, 0x50, 0xca, 0xc0, 0x9d,
	0xc1, 0xd7, 0x5f, 0xff, 0xbe, 0x5b, 0x5d, 0xf4, 0x9c, 0x14, 0x92, 0xcd, 0x42, 0xb3, 0x59, 0x88,
	0x92, 0xbc, 0xb5, 0x3b, 0xed, 0x25, 0x9f, 0xb9, 0xff, 0x05, 0xfd, 0x07, 0xf0, 0xe6, 0x5a, 0xbf,
	0x13, 0x86, 0x07, 0xe6, 0x2d, 0x69, 0xd6, 0x81, 0x79, 0xcb, 0xea, 0xe3, 0xbc, 0x48, 0xf3, 0x3e,
	0x43, 0x4f, 0x2f, 0x91, 0xb7, 0xfb, 0xe1, 0xe7, 0xc2, 0x06, 0xf3, 0x85, 0x0d, 0xfe, 0x2e, 0x6c,
	0xf0, 0x6d, 0x69, 0x57, 0xe6, 0x4b, 0xbb, 0xf2, 0x7b, 0x69, 0x57, 0xde, 0xf7, 0x02, 0xae, 0x3f,
	0x26, 0x2e, 0xf6, 0xe4, 0xf8, 0x42, 0x06, 0xcd, 0xcc, 0x61, 0xed, 0xa1, 0x67, 0x11, 0x53, 0xee,
	0xb5, 0xf4, 0x77, 0xf0, 0xf8, 0x34, 0x00, 0x00, 0xff, 0xff, 0x54, 0xab, 0xca, 0x1b, 0xb8, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a documents by id.
	Documents(ctx context.Context, in *QueryGetDocumentsRequest, opts ...grpc.CallOption) (*QueryGetDocumentsResponse, error)
	// Queries a list of documents items.
	DocumentsAll(ctx context.Context, in *QueryAllDocumentsRequest, opts ...grpc.CallOption) (*QueryAllDocumentsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Documents(ctx context.Context, in *QueryGetDocumentsRequest, opts ...grpc.CallOption) (*QueryGetDocumentsResponse, error) {
	out := new(QueryGetDocumentsResponse)
	err := c.cc.Invoke(ctx, "/ElectronicSignaturesIndustries.xdvnode.xdvnode.Query/Documents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DocumentsAll(ctx context.Context, in *QueryAllDocumentsRequest, opts ...grpc.CallOption) (*QueryAllDocumentsResponse, error) {
	out := new(QueryAllDocumentsResponse)
	err := c.cc.Invoke(ctx, "/ElectronicSignaturesIndustries.xdvnode.xdvnode.Query/DocumentsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a documents by id.
	Documents(context.Context, *QueryGetDocumentsRequest) (*QueryGetDocumentsResponse, error)
	// Queries a list of documents items.
	DocumentsAll(context.Context, *QueryAllDocumentsRequest) (*QueryAllDocumentsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Documents(ctx context.Context, req *QueryGetDocumentsRequest) (*QueryGetDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Documents not implemented")
}
func (*UnimplementedQueryServer) DocumentsAll(ctx context.Context, req *QueryAllDocumentsRequest) (*QueryAllDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocumentsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Documents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Documents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ElectronicSignaturesIndustries.xdvnode.xdvnode.Query/Documents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Documents(ctx, req.(*QueryGetDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DocumentsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DocumentsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ElectronicSignaturesIndustries.xdvnode.xdvnode.Query/DocumentsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DocumentsAll(ctx, req.(*QueryAllDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ElectronicSignaturesIndustries.xdvnode.xdvnode.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Documents",
			Handler:    _Query_Documents_Handler,
		},
		{
			MethodName: "DocumentsAll",
			Handler:    _Query_DocumentsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xdvnode/query.proto",
}

func (m *QueryGetDocumentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDocumentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDocumentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDocumentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDocumentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDocumentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Documents != nil {
		{
			size, err := m.Documents.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDocumentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDocumentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDocumentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDocumentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDocumentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDocumentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Documents) > 0 {
		for iNdEx := len(m.Documents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Documents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetDocumentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetDocumentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Documents != nil {
		l = m.Documents.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDocumentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDocumentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Documents) > 0 {
		for _, e := range m.Documents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetDocumentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDocumentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDocumentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDocumentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDocumentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDocumentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Documents == nil {
				m.Documents = &Documents{}
			}
			if err := m.Documents.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDocumentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDocumentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDocumentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDocumentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDocumentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDocumentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Documents = append(m.Documents, &Documents{})
			if err := m.Documents[len(m.Documents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
